"""Fail builds if the released catalog no longer matches the Sheets audit."""
import hashlib
import json
from pathlib import Path


def check(root):
    raw = (root / 'assets/shops.json').read_bytes()
    shops = json.loads(raw)
    audit = json.loads((root / 'docs/data/sheet-sync-audit.json').read_text(encoding='utf-8'))
    registry = json.loads((root / 'tool/sheet_sources.json').read_text(encoding='utf-8'))
    # Git can use CRLF in a Windows checkout; the canonical generated bytes use LF.
    assert hashlib.sha256(raw.replace(b'\r\n', b'\n')).hexdigest() == audit['catalogSha256'], 'Catalog changed without a new Sheets audit'
    ids = [s['id'] for s in shops]
    source_ids = [i for t in audit['tabs'] for i in t['ids']]
    closed = {s['id'] for s in audit['closed']}
    assert len(ids) == len(set(ids)), 'Duplicate catalog IDs'
    assert len(source_ids) == len(set(source_ids)) == audit['sourceRows'], 'Duplicate/missing source IDs'
    assert not set(ids) & closed, 'Closed shop in catalog'
    assert set(ids) | closed == set(source_ids), 'Unaccounted source rows'
    key = lambda t: (t['spreadsheetId'], t['sheetId'], t['title'])
    assert {key(t) for t in registry['tabs']} == {key(t) for t in audit['tabs']}, 'Source tab missing from audit'
    unmapped = set()
    for s in shops:
        assert s.get('name') and s.get('prefecture') and s.get('municipality'), 'Missing location identity'
        if s['lat'] is None and s['lon'] is None:
            unmapped.add(s['id'])
        else:
            assert isinstance(s['lat'], (float, int)) and isinstance(s['lon'], (float, int)), 'Invalid coordinates'
            assert 20 <= s['lat'] <= 46 and 122 <= s['lon'] <= 154, 'Coordinates outside Japan'
    assert unmapped == {s['id'] for s in audit['directoryOnly']}, 'Missing addressless shops'
    assert len(shops) - len(unmapped) == audit['mapped'], 'Mapped count mismatch'
    print(f"Catalog OK: {len(shops)} listed, {len(unmapped)} directory-only, {len(closed)} closed; {len(source_ids)} source rows accounted for")


if __name__ == '__main__':
    check(Path(__file__).resolve().parents[1])
